# Generated by Django 2.2.4 on 2020-03-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiryeng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=64)),
                ('contact', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=16)),
                ('fax', models.CharField(max_length=16)),
                ('usertext', models.TextField()),
                ('message', models.TextField()),
                ('date_of_inquiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Textuploadeng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertext', models.TextField()),
                ('result', models.CharField(max_length=8)),
                ('date_of_upload', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
