# Generated by Django 2.2.4 on 2020-08-18 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_inquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'permissions': (('can_check_backend', 'can log in backend site'),)},
        ),
    ]
