# Generated by Django 2.2.4 on 2020-08-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20200818_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='textupload',
            name='company',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
