# Generated by Django 2.2.4 on 2020-08-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_textupload_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='textupload',
            name='product',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
