# Generated by Django 2.2.4 on 2020-09-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_inquiry_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='email',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
