# Generated by Django 2.2.4 on 2020-09-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_inquiry_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='textupload',
            name='email',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='textupload',
            name='phone',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
